### ISSUE TITLE
PR: Insertion Sort

### ISSUE THREAD

**Issue by amilajack** [amilajack/js-algorithms#122]

**Comment by hamirmahal** [comment]
It looks like you already have an InsertionSort.js file, but I'm having trouble running it in Visual Studio Code. I'm getting the following error, without quotation marks: "SyntaxError: Unexpected token 'export'".

I can contribute an implementation of InsertionSort if you want me to, but I'd probably have to write it from scratch as opposed to getting the InsertionSort.js file already in the repository to work on my device, since I'm unfamiliar with Node.js.

Is that fine? Sorry I couldn't get to the Bubble Sort PR in time.

**Comment by amilajack** [comment]
Thanks for pointing this out! This should be closed then

**Comment by amilajack** [comment]
@hamirmahal Fee free to work on #35

**Comment by hamirmahal** [comment]
> @hamirmahal Fee free to work on #35

Sounds good! Checking it out.

**Comment by vikr01** [comment]
> I'm having trouble running it in Visual Studio Code. I'm getting the following error, without quotation marks: "SyntaxError: Unexpected token 'export'".

@hamirmahal You should read the README, it explains it well.
